name = "new-mc-landing-page"
compatibility_date = "2025-12-31"
pages_build_output_dir = ".vercel/output/static"

[site]
bucket = ".vercel/output/static"

[[rules]]
type = "Text"
globs = ["**/*.html", "**/*.txt"]
fallthrough = true

[[rules]]
type = "Data"
globs = ["**/*"]
fallthrough = true
